### ISSUE TITLE
error netbean build

### ISSUE THREAD

**Issue by CodexTech0X** [thisisnzed/Pandora#10]
i have error to build in netbean any help 
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Master: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by thisisnzed** [comment]
https://exerror.com/failed-to-execute-goal-org-apache-maven-pluginsmaven-compiler-plugin3-8-0compile-default-compile-on-project-demo-fatal-error-compiling-invalid-target-release-11/

**Comment by PandoricGalaxy** [comment]
> i have error to build in netbean any help Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Master: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
> 
> To see the full stack trace of the errors, re-run Maven with the -e switch. Re-run Maven using the -X switch to enable full debug logging.
> 
> For more information about the errors and possible solutions, please read the following articles: [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

if u succesfully compiled and ran it pls tell how cause im getting error of classnotfound
