### ISSUE TITLE
Exception in Application Start Method

### ISSUE THREAD

**Issue by PandoricGalaxy** [thisisnzed/Pandora#11]
![image](https://user-images.githubusercontent.com/86944806/164041661-7683e07f-a568-415e-9883-f833dbfa4711.png)
Earlier it said classnotfound but after i added mainClass to pom.xml and ran,
it now shows this.

i added this to pom.xml

> <build>
     <plugins>
         <plugin> 
    
                    
    
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.1.0</version>
                    <configuration>
                      <archive>
                        <manifest>
    
                        
                          <mainClass>org.pandora.master.launch.Launch</mainClass>
    
                        </manifest>
                      </archive>
                    </configuration>
        </plugin>
     </plugins>
    </build>

my pom.xml:
https://pastebin.com/LS8KXUhf

**Comment by thisisnzed** [comment]
Without the error, I can’t help you

**Comment by PandoricGalaxy** [comment]
> Without the error, I can’t help you

u could help if u showed in detail how to compile but ik u wont as u said.
doing -e or -X gives nothing new just about the config is error

**Comment by thisisnzed** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/76526948/164046758-e5ab7bb2-b161-44f1-ad40-2d10d49590e4.png)

**Comment by PandoricGalaxy** [comment]
Did u make any changes to any file after cloning the repo?
Like I did to pom.xml?
