### ISSUE TITLE
[Resolved] compilation 

### ISSUE THREAD

**Issue by Strannik74** [thisisnzed/Pandora#2]
hello
I am newbie how to compile this correctly

**Comment by GSA001** [comment]
I also would like ask for a slightly better tutorial.

When I run Master.Java i keep getting the error message Java.lang.classnotfoundexcpetion: Master

**Comment by thisisnzed** [comment]
Hello,

On this github, I only share a few projects that I am developing on my own and so I am not here to make you a tutorial to compile the project. On the other hand, you can search on the internet how to compile a github project if you really want to use this code.

I advise you to learn Java by yourself and use Pandora code when you really need it, you will learn faster!

Have a good day

**Comment by GSA001** [comment]
so we do need to compile this, this is good to know.

**Comment by als-71** [comment]
Sir can you plz release one compiled project for us

**Comment by thisisnzed** [comment]
> so we do need to compile this, this is good to know.

Exactly

> Sir can you plz release one compiled project for us

There will be no public release, you have to compile it yourself if you really want to use it

**Comment by als-71** [comment]
Ok Sir but can you just instruct us ? please

**Comment by thisisnzed** [comment]
No, search for yourself on the internet. I'm just sharing my code.
