### ISSUE TITLE
(Master) Connection refused from xxx.xxx.xxx.xxx. due to forbidden IP

### ISSUE THREAD

**Issue by w00ki3z** [thisisnzed/Pandora#3]
Hi! When I start the server and after connecting I have the inscription "Trying to connect to xxx.xxx.xxx.xxx:11111" and that's it. What could be the problem?

**Comment by thisisnzed** [comment]
Hi,
You need to add the following argument : -allowed ";your_ip;" or -allowed "all"

**Comment by w00ki3z** [comment]
Sorry man! But after I have created an agent and run it, nothing appears in the agents tab. I specify the IP address and PORT of the server, but no further action occurs

**Comment by PandoricGalaxy** [comment]
Hey @w00ki3z How did you compile the master? I need help on it since i cant compile issue 
https://github.com/thisisnzed/Pandora/issues/7
