### ISSUE TITLE
Problem with agent

### ISSUE THREAD

**Issue by w00ki3z** [thisisnzed/Pandora#4]
Sorry man! But after I have created an agent and run it, nothing appears in the agents tab. I specify the IP address and PORT of the server, but no further action occurs

_Originally posted by @w00ki3z in https://github.com/thisisnzed/Pandora/issues/3#issuecomment-1073044587_

**Comment by Frido-Cpp** [comment]
Hey Man, Tried Port forwarding?

**Comment by w00ki3z** [comment]
Hi! Can you explain in more detail for this program?

**Comment by thisisnzed** [comment]
Refer to the classes related to the autoupdate on the Agent side.
Indeed, you need to have your own update check server because otherwise the agent cannot check if it is up to date and therefore cannot connect.

**Comment by w00ki3z** [comment]
I didn't quite understand, that is, do I need to change the links to my server in the agent classes? And put the agent file that I created on the server?

**Comment by PandoricGalaxy** [comment]
how did you compile it?

**Comment by thisisnzed** [comment]
No, search for yourself on the internet. I'm just sharing my code.
