### ISSUE TITLE
Some kind of server warning

### ISSUE THREAD

**Issue by Frido-Cpp** [thisisnzed/Pandora#5]
after building server and tryna launch i get this 
WARNING: Please consider reporting this to the maintainers of org.pandora.server.launch.Launch
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[23:17:21] Server started with port 11111!

**Comment by thisisnzed** [comment]
You are probably using a version of java higher than 8.

I don’t think that’s going to be a problem, because it’s just a warning, not a error

**Comment by Frido-Cpp** [comment]
ooh okay Yeah. I just Discovered that was the problem. I'm using JDK 17 lol

**Comment by PandoricGalaxy** [comment]
Hey Bro how did you compile it?

**Comment by thisisnzed** [comment]
Search for yourself on the internet. I'm just sharing my code.
