### ISSUE TITLE
Unable to Compile with maven

### ISSUE THREAD

**Issue by PandoricGalaxy** [thisisnzed/Pandora#7]
https://github.com/thisisnzed/Pandora/issues/6#issue-1174571307
Why was the issue closed without any reply?

**Comment by SMods11** [comment]
> [#6 (comment)](https://github.com/thisisnzed/Pandora/issues/6#issue-1174571307)
> Why was the issue closed without any reply?

java -jar Master-1.0-SNAPSHOT.jar
in cmd probably

**Comment by PandoricGalaxy** [comment]
@SMods11 
![image](https://user-images.githubusercontent.com/86944806/159415211-50567d72-6891-4b59-9378-b7f9ca45b1fd.png)
This is shown, then what to do?

**Comment by PandoricGalaxy** [comment]
I ran this then:
jar cmvf CLASSES/META-INF/MANIFEST.MF Master-1.0-SNAPSHOT.jar
And it gave this:
![image](https://user-images.githubusercontent.com/86944806/159415786-e5e7e64d-4c23-4550-a426-fdf495e7a944.png)

**Comment by Frido-Cpp** [comment]
The Master is a Javafx application

**Comment by thisisnzed** [comment]
Search for yourself on the internet. I'm just sharing my code.

Check on youtube if you want to compile this virus.

**Comment by PandoricGalaxy** [comment]
> The Master is a Javafx application

What do you mean?
What do i have to do then?

**Comment by PandoricGalaxy** [comment]
> Search for yourself on the internet. I'm just sharing my code.
> 
> Check on youtube if you want to compile this virus.

Youtube doesnt have it thats the problem!

**Comment by PandoricGalaxy** [comment]
> The Master is a Javafx application
@Frido-Cpp 

What does that mean?

**Comment by Frido-Cpp** [comment]
I'm having a problem too with executing the master. maybe it isn't compatible with my java version or my 32 bit laptop. who knows.

**Comment by PandoricGalaxy** [comment]
@thisisnzed Can you pls help here? I am unable to find any solution to this problem online:
![image](https://user-images.githubusercontent.com/86944806/159657157-8621884c-f4a3-419d-9c72-706ff4f1bdc3.png)
Just help me once please. If im able to run it then if someone else has the problem i could help them but rn i cannot find any way to fix this. Please understand and help me.

**Comment by thisisnzed** [comment]
There's no point in spamming issues for the same issue when I said I won't support it!

**Comment by thisisnzed** [comment]
There's no point in spamming issues for the same issue when I said I won't support it!
