### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by Frido-Cpp** [thisisnzed/Pandora#8]
works fine but doesn't display in browser

java -cp Server-1.0-SNAPSHOT.jar org.pandora.server.launch.Launch 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

[20:18:31] Server started with port 443!
[DEBUG/INFO] GET / HTTP/1.1
[DEBUG/INFO] Host: xxx.xxxx.xxx:443
[DEBUG/INFO] User-Agent: Mozilla/5.0 (X11; Linux i686; rv:78.0) Gecko/20100101 Firefox/78.0
[DEBUG/INFO] Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
[DEBUG/INFO] Accept-Language: en-US,en;q=0.5
[DEBUG/INFO] Accept-Encoding: gzip, deflate

**Comment by Frido-Cpp** [comment]
I'm having difficulties installing and running the master due to the javafx issue, I'm using openjdk8 and I installed openjfx with apt, but now I'm frozen, i've I've done enough research, and still leads me back here

**Comment by thisisnzed** [comment]
Search for yourself on the internet. I'm just sharing my code.

Check on youtube if you want to compile this virus.

Otherwise, it's not an HTTP Server

**Comment by Frido-Cpp** [comment]
I understand you bro, But It could have been better if you just said "Use jdk8, Use mvn, The Master is a javafx application", Anyways Thanks very much for the hardwork on this.

**Comment by thisisnzed** [comment]
If you do not know how to compile a program, there is no point in trying to compile this virus..

**Comment by Frido-Cpp** [comment]
There's a difference bro. I may not be good with java, but I develop malware(Research purposes) with other languages, So When I see a Ratnet as good as this, my aim is to study how it works and Implement it in the language I'm good at.

**Comment by PandoricGalaxy** [comment]
> I'm having difficulties installing and running the master due to the javafx issue, I'm using openjdk8 and I installed openjfx with apt, but now I'm frozen, i've I've done enough research, and still leads me back here

Are you also getting this?:
![image](https://user-images.githubusercontent.com/86944806/159649245-8f90680a-0aa0-4421-823b-67df4bbeddee.png)

**Comment by Frido-Cpp** [comment]
yes, I don't think it has to be launched that way, still figuring things out, I'm good with other languages not java

**Comment by PandoricGalaxy** [comment]
> yes, I don't think it has to be launched that way, still figuring things out, I'm good with other languages not java

then how is it supposed to be launched? Ive tried searching the web for hours but still no rersult

**Comment by Frido-Cpp** [comment]
Still figuring out

**Comment by thisisnzed** [comment]
You just didn’t compile all the classes well

**Comment by PandoricGalaxy** [comment]
> You just didn’t compile all the classes well

That's what I want to know how to do! I can't figure out how to compile it! Can you pls tell me how or list a tutorial?

**Comment by thisisnzed** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/76526948/160243560-2fca3ef1-5a05-44da-b507-69e6a4d8febc.png)

**Comment by PandoricGalaxy** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/76526948/160243560-2fca3ef1-5a05-44da-b507-69e6a4d8febc.png)

You added this recently after our issue

**Comment by Trusthoodies** [comment]
> Still figuring out
Did you find it?
